logging:
 level:
  org.springframework.web: ERROR
  com.mugowanjogu.dasboot: DEBUG

spring:
  profiles:
    active: dev

  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    url: jdbc:h2:/Users/mugo/dev/h2/das-boot
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    tomcat:
      max-active: 10
      max-idle: 8
      max-wait: 10000
      min-evictable-idle-time-millis: 1000
      min-idle: 8
      time-between-eviction-runs-millis: 1
      
  flyway:
    baseline-on-migrate: true
    
  jpa:
    hibernate:
      ddl-auto: none 

# uses the same db as primary datasource but could point to another db      
flyway: 
  datasource:
    url: jdbc:h2:/Users/mugo/dev/h2/das-boot
    username: sa
    password: 
    driver-class-name: org.h2.Driver